steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '--build-arg',
        'REACT_APP_GCP_API_KEY=${_GCP_API_KEY}',
        '--build-arg',
        'REACT_APP_GCP_CLIENT_ID=${_GCP_CLIENT_ID}',
        '--tag',
        'gcr.io/kwcay/jayne-eats-prototype:latest',
        '--target',
        'prod',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/kwcay/jayne-eats-prototype:latest']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run',
        'deploy',
        'jayne-eats-prototype',
        '--allow-unauthenticated',
        '--image',
        'gcr.io/kwcay/jayne-eats-prototype:latest',
        '--platform',
        'managed',
        '--region',
        'us-east1',
      ]

images:
  - gcr.io/kwcay/jayne-eats-prototype
